#define EMBEDDED

#define HAVE_MALLOC
#define HAVE_INIT_SCRIPT
#define HAVE_BZERO
#define HAVE_TICK

#define HAVE_EHCILL

#define ENABLE_LOG_ERROR

#if UNITTEST == 1
#	define ENABLE_LOG_INFO
#	define ENABLE_LOG_DEBUG
#endif

#define HCI_ACL_PAYLOAD_SIZE 102
#define HAVE_BLE 1

//
#if 0
#define MAX_SPP_CONNECTIONS 5


#define MAX_NO_HCI_CONNECTIONS (MAX_SPP_CONNECTIONS + 3)
#define MAX_NO_L2CAP_SERVICES  5
#define MAX_NO_L2CAP_CHANNELS  (3 + MAX_SPP_CONNECTIONS)
#define MAX_NO_RFCOMM_MULTIPLEXERS MAX_SPP_CONNECTIONS
#define MAX_NO_RFCOMM_SERVICES 4
#define MAX_NO_RFCOMM_CHANNELS MAX_SPP_CONNECTIONS
#define MAX_NO_DB_MEM_DEVICE_LINK_KEYS  0
#define MAX_NO_DB_MEM_DEVICE_NAMES 0
#define MAX_NO_DB_MEM_SERVICES 0
#endif